Implement tab jumping (#49)
* Small fixes
* Try to implement a Mutation Observer — I am getting something wrong here… Firefox says “Uncaught TypeError: Node.contains: Argument 1 does not implement interface Node.” and Chrome says “Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node’.”
* Style updates to support buttons — We switch from anchors to buttons since these are on page events, not off page URLs
* Rendered CSS
* Refactor to use event listener on container
* Updates for deprecated math functions
* Rendered CSS

Co-authored-by: Rob Aubin <rob@oomphinc.com>